name = "ObservationalCorrectness"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ObservationalCorrectness"]

[leanOptions]
pp.unicode.fun = false # pretty-prints `fun a ↦ b`
autoImplicit = true
relaxedAutoImplicit = true
weak.linter.mathlibStandardSet = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "ObservationalCorrectness"
