[package]
name = "aig-manip"
version = "0.1.0"
edition = "2024"

[dependencies]
aig = "0.4.5"
clap = { version = "4.5.41", features = ["derive"] }
rIC3 = "1.4.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
vcd = "0.7.0"
